use crate::models::Session;
use crate::storage::{SessionStorage, StorageError};
use std::thread;
use std::time::Duration;

/// Replay a recorded session with timing
pub fn replay_session(
    storage: &SessionStorage,
    session_id: &str,
    speed: f64,
    no_interact: bool,
) -> Result<(), StorageError> {
    // Read the session file
    let commands_path = storage.sessions_dir().join(format!("{session_id}.json"));
    let content = std::fs::read_to_string(&commands_path)?;
    let session: Session = serde_json::from_str(&content)
        .map_err(|e| StorageError::SerializationError(e.to_string()))?;

    println!("=== Replaying session: {} ===", session.name);
    println!(
        "Host: {}@{} | Commands: {} | Duration: {:.1}s",
        session.username,
        session.hostname,
        session.commands.len(),
        session.duration.as_secs_f64()
    );
    println!("Speed: {:.1}x", speed);
    println!("---");

    let speed_multiplier = if speed <= 0.0 { 1.0 } else { speed };

    for cmd in &session.commands {
        // Show command with timing info
        println!(
            "\n[Command #{}] exit={} {:.2}s",
            cmd.sequence,
            cmd.exit_code,
            cmd.duration.as_secs_f64()
        );
        println!("$ {}", cmd.command);
        println!("cwd: {}", cmd.cwd);

        if !cmd.stdout_preview.is_empty() {
            println!("--- stdout ---");
            if cmd.stdout_truncated {
                println!("{}", cmd.stdout_preview);
                println!("[truncated]");
            } else {
                println!("{}", cmd.stdout_preview);
            }
        }

        if !cmd.stderr_preview.is_empty() {
            println!("--- stderr ---");
            if cmd.stderr_truncated {
                println!("{}", cmd.stderr_preview);
                println!("[truncated]");
            } else {
                println!("{}", cmd.stderr_preview);
            }
        }

        // Real-time replay: sleep proportional to command duration
        if !no_interact && speed_multiplier > 0.0 {
            let real_sleep = cmd.duration.as_secs_f64() / speed_multiplier;
            let sleep_ms = (real_sleep * 1000.0) as u64;
            // Cap sleep at 2 seconds to avoid long waits
            let capped_sleep = std::cmp::min(sleep_ms, 2000);
            if capped_sleep > 0 {
                thread::sleep(Duration::from_millis(capped_sleep));
            }
        }
    }

    println!("\n---");
    println!(
        "Replay complete. {} commands replayed.",
        session.commands.len()
    );

    Ok(())
}

/// Format a session as a bash script (for non-interactive replay)
#[allow(dead_code)]
pub fn format_as_script(session: &Session) -> Result<String, StorageError> {
    let mut script = String::new();

    script.push_str("#!/bin/bash\n");
    script.push_str(&format!("# Session: {}\n", session.name));
    script.push_str(&format!(
        "# Recorded: {} - {} ({:.1}s)\n",
        session.start_time,
        session.end_time,
        session.duration.as_secs_f64()
    ));
    script.push_str("# Generated by session-recorder\n\n");

    script.push_str("set -e\n\n");

    for cmd in &session.commands {
        script.push_str(&format!(
            "# [Command #{}] exit={} {:.2}s\n",
            cmd.sequence,
            cmd.exit_code,
            cmd.duration.as_secs_f64()
        ));
        script.push_str(&format!("cd {}\n", cmd.cwd));
        script.push_str(&format!("{}\n\n", cmd.command));
    }

    Ok(script)
}
